### ISSUE TITLE
Recipe for rapic.y failed, rapic.y not found

### ISSUE THREAD

**Issue by BerendWijers** [adokter/rsl#7]
Hi,

I'm trying to compile vol2bird-master and I'm running into a snag compiling RSL. I remember you recently updating RSL to provide compatibility with h52.2, maybe it caused this error?

Anyways, I was following the "Install ubuntu.md" from vol2bird-master and during compilation of RSL I get the error:

```
/bin/bash ./ylwrap rapic.y y.tab.c rapic.c y.tab.h rapic.h y.output rapic.output -- yacc -d -p rapic
./ylwrap: line 86: rapic.y: command not found
Makefile:512: recipe for target 'rapic.c' failed
```
I've also installed librsl-dev and librsl1 just to be sure - no avail.

```
 apt search librsl
Sorting... Done
Full Text Search... Done
librsl-dev/bionic,now 1.43-1.2build1 amd64 [installed]
  Development files for RSL

librsl-doc/bionic,bionic 1.43-1.2build1 all
  HTML documentation for RSL

librsl1/bionic,now 1.43-1.2build1 amd64 [installed]
  TRMM Radar Software Library
```

Info:
```
uname -r
4.15.0-39-generic

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
I'm pretty stuck right now and I'm not sure if I'm missing a silly thing or that it's something on this RSL's end.

**Comment by adokter** [comment]
Hi @BerendWijers, the RSL library is for reading NEXRAD data from USA, so you won't need it for European data (just skip the rsl installation and compile vol2bird without the --wit-rsl flag)

Nonetheless, thanks for spotting this error, indeed the ubuntu install instructions were out of date since a recent fix that accounts for a different encoding of newer NEXRAD file. I've added that now, so hope you can compile it.

**Comment by BerendWijers** [comment]
Thank you for the pointers! Tomorrow I will compile and I'll leave some feedback if it does or does not work so you know if your fix works (for future purposes as I indeed mainly work with European data).

Anyways, thanks for investigating this, much appreciated!
